language: go
go: 1.2
before_script:
  - npm install --quiet -g karma
  - npm install
install:
  - go get github.com/stretchr/testify/assert
script:
  - cd marto && go test -v
  - cd .. && karma start --single-run --browsers PhantomJS app/config/karma.conf.js