language: go
go: 1.2

before_script:
  - npm install --quiet -g karma
  - npm install

install:
  - go get github.com/stretchr/testify/assert
  - go get labix.org/v2/mgo
  - go get github.com/gorilla/mux

services:
  - mongodb

script:
  - bash test_all